// src/lib/default-content-getters.ts

import type { SlideContentData, HomeContentData, ServicesPageData, HowItWorksContentData, ContactContentData } from '@/lib/content-types';

export const getInitialSlideshowData = (): SlideContentData[] => [
  {
    id: 1,
    imageUrl: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzEzMjR8MHwxfHNlYXJjaHwxfHxjb21tdW5pdHklMjBzdXBwb3J0JTIwdGVhbXxlbnwwfHx8fDE3MjM4MDQwODV8MA&ixlib=rb-4.0.3&q=80&w=1600',
    imageHint: 'community support team',
    altText_de: 'Gruppe von Menschen die zusammenarbeiten mit Technologie',
    altText_en: 'Diverse group of people collaborating with technology',
    title_de: 'Willkommen bei Nginxify Assist!',
    title_en: 'Welcome to Nginxify Assist!',
    description_de: 'Ehrenamtliche IT-Unterstützung für Vereine und Einzelpersonen. Wir helfen Ihnen, die digitale Welt zu meistern.',
    description_en: 'Volunteer IT support for clubs and individuals. We help you navigate the digital world.',
    ctaText_de: 'Mehr Erfahren',
    ctaText_en: 'Learn More',
    ctaLink: '/how-it-works',
  },
  {
    id: 2,
    imageUrl: 'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzEzMjR8MHwxfHx3ZWJzaXRlJTIwY3JlYXRpb24lMjBsYXB0b3B8ZW58MHx8fHwxNzIzODA0MTM3fDA&ixlib=rb-4.0.3&q=80&w=1600',
    imageHint: 'website creation laptop',
    altText_de: 'Laptop Bildschirm zeigt den Prozess der Webseitenerstellung',
    altText_en: 'Laptop screen showing website design process',
    title_de: 'Hilfe bei Ihrer Webseite benötigt?',
    title_en: 'Need Help with Your Website?',
    description_de: 'Von der grundlegenden Einrichtung bis zur Beratung zu Online-Tools – unsere Freiwilligen helfen gerne.',
    description_en: 'From basic setup to advice on online tools, our volunteers are here to assist.',
    ctaText_de: 'Unsere Leistungen',
    ctaText_en: 'Our Services',
    ctaLink: '/services',
  },
  {
    id: 3,
    imageUrl: 'https://images.unsplash.com/photo-1573496774439-972004891aed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w2MzEzMjR8MHwxfHNlYXJjaHwxfHx2b2x1bnRlZXIlMjBoZWxwaW5nJTIwY29tcHV0ZXJ8ZW58MHx8fHwxNzIzODA0MTcxfDA&ixlib=rb-4.0.3&q=80&w=1600',
    imageHint: 'volunteer helping computer',
    altText_de: 'Freundlicher Freiwilliger hilft jemandem am Computer',
    altText_en: 'Friendly volunteer assisting someone with a computer',
    title_de: 'Unterstützung durch Freiwillige, für die Gemeinschaft',
    title_en: 'Support by Volunteers, For the Community',
    description_de: 'Engagierte Technik-Enthusiasten bieten ihre Zeit und Fähigkeiten an.',
    description_en: 'Passionate tech enthusiasts offering their time and skills.',
    ctaText_de: 'Hilfe Anfragen',
    ctaText_en: 'Request Help',
    ctaLink: '/contact',
  },
];

export const getInitialHomeContent = (): HomeContentData => ({
  pageTitle_de: 'nginxify Hilfe: Ehrenamtliche IT-Unterstützung für Vereine & Einzelpersonen',
  pageTitle_en: 'Nginxify Help: Volunteer IT Support for Clubs & Individuals',
  pageDescription_de: 'Wir helfen digital – kostenlos oder gegen eine freiwillige Spende. Unsere Mission ist es, gemeinnützige Organisationen und Privatpersonen mit IT-Herausforderungen zu unterstützen.',
  pageDescription_en: 'We help digitally – free of charge or for a voluntary donation. Our mission is to support non-profit organizations and private individuals with IT challenges.',
  clubsTitle_de: 'Für Vereine & Organisationen',
  clubsTitle_en: 'For Clubs & Organizations',
  clubsDescription_de: 'Unterstützung für gemeinnützige Projekte.',
  clubsDescription_en: 'Support for non-profit projects.',
  clubsText_de: 'Wir bieten grundlegende Hilfe bei der Erstellung von Webseiten, der Einrichtung von Online-Tools, oder bei allgemeinen IT-Fragen, damit Sie sich auf Ihre Kernarbeit konzentrieren können.',
  clubsText_en: 'We offer basic help with website creation, setting up online tools, or general IT questions, so you can focus on your core work.',
  individualsTitle_de: 'Für Privatpersonen',
  individualsTitle_en: 'For Individuals',
  individualsDescription_de: 'Hilfe bei alltäglichen IT-Problemen.',
  individualsDescription_en: 'Help with everyday IT problems.',
  individualsText_de: 'Brauchen Sie Hilfe mit Ihrem Computer, Smartphone oder haben Sie Fragen zur Online-Sicherheit? Wir unterstützen Sie bei einfachen IT-Herausforderungen.',
  individualsText_en: 'Need help with your computer, smartphone, or have questions about online security? We support you with simple IT challenges.',
  viewDetailsButton_de: 'Details ansehen',
  viewDetailsButton_en: 'View Details',
  howItWorksTitle_de: 'Wie funktioniert unsere Hilfe?',
  howItWorksTitle_en: 'How does our help work?',
  howItWorksDescription_de: 'Unsere Unterstützung basiert auf ehrenamtlichem Engagement. Erfahren Sie mehr über den Prozess und wie Sie Hilfe anfordern können.',
  howItWorksDescription_en: 'Our support is based on volunteer work. Learn more about the process and how you can request help.',
  howItWorksButton_de: 'So Funktioniert\'s',
  howItWorksButton_en: 'How It Works',
  slideshowItems: getInitialSlideshowData(),
});


export const getInitialServicesPageContent = (): ServicesPageData => ({
  pageTitle_de: 'Unsere Leistungen',
  pageTitle_en: 'Our Services',
  pageDescription_de: 'Wir bieten ehrenamtliche IT-Unterstützung für gemeinnützige Organisationen und Privatpersonen. Unser Fokus liegt auf grundlegender Hilfe und Beratung.',
  pageDescription_en: 'We offer volunteer IT support for non-profit organizations and individuals. Our focus is on basic help and advice.',
  clubSectionTitle_de: 'Für Vereine & Organisationen',
  clubSectionTitle_en: 'For Clubs & Organizations',
  clubSectionDescription_de: 'Wir unterstützen gemeinnützige Vereine und Organisationen dabei, ihre digitale Präsenz aufzubauen und grundlegende IT-Herausforderungen zu meistern. Bitte beachten Sie, dass wir keine komplexen, professionellen Großprojekte übernehmen können.',
  clubSectionDescription_en: 'We support non-profit clubs and organizations in building their digital presence and overcoming basic IT challenges. Please note that we cannot take on complex, professional large-scale projects.',
  individualSectionTitle_de: 'Für Privatpersonen',
  individualSectionTitle_en: 'For Individuals',
  individualSectionDescription_de: 'Wir helfen Ihnen bei alltäglichen IT-Problemen und Fragen rund um Computer, Smartphone und Internet.',
  individualSectionDescription_en: 'We help you with everyday IT problems and questions about computers, smartphones, and the internet.',
});

export const getInitialHowItWorksContent = (): HowItWorksContentData => ({
  pageTitle_de: 'So Funktioniert\'s',
  pageTitle_en: 'How It Works',
  pageDescription_de: 'Erfahren Sie mehr über unser ehrenamtliches Modell, wie Sie Hilfe anfordern können und was Sie erwarten können.',
  pageDescription_en: 'Learn more about our volunteer model, how to request help, and what to expect.',
  volunteerTitle_de: 'Ehrenamtliches Engagement',
  volunteerTitle_en: 'Volunteer Commitment',
  volunteerDescription_de: 'Unsere Hilfe wird von Freiwilligen geleistet, die ihre IT-Kenntnisse und Zeit zur Verfügung stellen, um anderen zu helfen. Wir sind eine Gemeinschaft von Technikbegeisterten, die Gutes tun wollen.',
  volunteerDescription_en: 'Our help is provided by volunteers who offer their IT skills and time to help others. We are a community of tech enthusiasts wanting to do good.',
  costTitle_de: 'Kostenlos & Spendenbasiert',
  costTitle_en: 'Free & Donation-Based',
  costDescription_de: 'Unsere grundlegende Unterstützung ist kostenlos. Freiwillige Spenden sind willkommen und helfen uns, eventuelle Kosten zu decken und die Initiative am Laufen zu halten. Es besteht jedoch keine Verpflichtung zur Spende.',
  costDescription_en: 'Our basic support is free. Voluntary donations are welcome and help us cover any costs and keep the initiative running. However, there is no obligation to donate.',
  requestTitle_de: 'Hilfe Anfordern',
  requestTitle_en: 'Requesting Help',
  requestDescriptionPart1_de: 'Der einfachste Weg, Unterstützung anzufragen, ist über unser ',
  requestDescriptionPart1_en: 'The easiest way to request support is via our ',
  requestDescriptionLink_de: 'Kontaktformular',
  requestDescriptionLink_en: 'Contact Form',
  requestDescriptionPart2_de: ' oder per E-Mail. Beschreiben Sie Ihr Anliegen möglichst genau, damit wir Ihre Anfrage besser einschätzen können.',
  requestDescriptionPart2_en: ' or by email. Please describe your issue as accurately as possible so we can better assess your request.',
  expectationTitle_de: 'Erwartungsmanagement',
  expectationTitle_en: 'Expectation Management',
  expectationDescription_de: 'Da wir ehrenamtlich tätig sind, erfolgt die Hilfe nach Verfügbarkeit unserer Freiwilligen. Wir bemühen uns, zeitnah zu antworten, bitten aber um Verständnis, wenn es manchmal etwas dauern kann. Wir können nicht garantieren, jedes Problem lösen zu können, geben aber unser Bestes.',
  expectationDescription_en: 'As we operate on a volunteer basis, help is provided based on the availability of our volunteers. We strive to respond promptly but ask for your understanding if it sometimes takes a little longer. We cannot guarantee to solve every problem, but we do our best.',
  whoTitle_de: 'Wer wir sind',
  whoTitle_en: 'Who We Are',
  whoDescription_de: 'Wir sind eine Gruppe von IT-interessierten Einzelpersonen, die ihre Fähigkeiten nutzen möchten, um gemeinnützigen Organisationen und Privatpersonen bei technischen Herausforderungen unter die Arme zu greifen.',
  whoDescription_en: 'We are a group of IT-interested individuals who want to use our skills to help non-profit organizations and individuals with technical challenges.',
  donationsTitle_de: 'Spendenverwendung (Optional)',
  donationsTitle_en: 'Use of Donations (Optional)',
  donationsDescription_de: 'Falls Spenden eingehen, werden diese transparent zur Deckung von Betriebskosten (z.B. Hosting der Webseite) oder zur Unterstützung spezifischer gemeinnütziger IT-Projekte verwendet.',
  donationsDescription_en: 'If donations are received, they will be used transparently to cover operating costs (e.g., website hosting) or to support specific non-profit IT projects.',
  ctaTitle_de: 'Bereit, Hilfe anzufragen?',
  ctaTitle_en: 'Ready to Request Help?',
  ctaDescription_de: 'Füllen Sie unser Kontaktformular aus oder schreiben Sie uns eine E-Mail. Wir freuen uns darauf, von Ihnen zu hören!',
  ctaDescription_en: 'Fill out our contact form or send us an email. We look forward to hearing from you!',
  ctaButton_de: 'Jetzt Kontakt aufnehmen',
  ctaButton_en: 'Contact Us Now',
});

export const getInitialContactContent = (): ContactContentData => ({
  pageTitle_de: 'Kontaktieren Sie Uns',
  pageTitle_en: 'Contact Us',
  pageDescription_de: 'Haben Sie eine Frage oder benötigen Sie IT-Unterstützung? Füllen Sie das Formular aus oder schreiben Sie uns eine E-Mail.',
  pageDescription_en: 'Have a question or need IT support? Fill out the form or send us an email.',
  formTitle_de: 'Anfrageformular',
  formTitle_en: 'Inquiry Form',
  alertTitle_de: 'Wichtige Informationen für Ihre Anfrage',
  alertTitle_en: 'Important Information for Your Request',
  alertDescription_de: 'Um Ihnen bestmöglich helfen zu können, beschreiben Sie Ihr Problem bitte so detailliert wie möglich. Geben Sie bei technischen Problemen bitte auch Informationen zu Ihrem Gerät (z.B. Betriebssystem, Modell) an, falls relevant.',
  alertDescription_en: 'To help us assist you best, please describe your problem in as much detail as possible. For technical issues, please also provide information about your device (e.g., operating system, model) if relevant.',
  nameLabel_de: 'Name',
  nameLabel_en: 'Name',
  namePlaceholder_de: 'Ihr Name',
  namePlaceholder_en: 'Your Name',
  emailLabel_de: 'E-Mail',
  emailLabel_en: 'Email',
  emailPlaceholder_de: 'ihre@email.de',
  emailPlaceholder_en: 'your@email.com',
  subjectLabel_de: 'Betreff',
  subjectLabel_en: 'Subject',
  subjectPlaceholder_de: 'Worum geht es?',
  subjectPlaceholder_en: 'What is it about?',
  messageLabel_de: 'Ihre Nachricht / Problembeschreibung',
  messageLabel_en: 'Your Message / Problem Description',
  messagePlaceholder_de: 'Beschreiben Sie Ihr Anliegen...',
  messagePlaceholder_en: 'Describe your concern...',
  messageDescription_de: 'Je detaillierter, desto besser können wir helfen.',
  messageDescription_en: 'The more detailed, the better we can help.',
  techDetailsLabel_de: 'Technische Details (Optional)',
  techDetailsLabel_en: 'Technical Details (Optional)',
  techDetailsPlaceholder_de: 'z.B. Betriebssystem, Gerätemodell, verwendete Software...',
  techDetailsPlaceholder_en: 'e.g., Operating system, device model, software used...',
  techDetailsDescription_de: 'Falls relevant für Ihr Problem.',
  techDetailsDescription_en: 'If relevant to your problem.',
  submitButton_de: 'Anfrage Senden',
  submitButton_en: 'Send Request',
  directContactTitle_de: 'Direkter Kontakt',
  directContactTitle_en: 'Direct Contact',
  emailInfoTitle_de: 'E-Mail',
  emailInfoTitle_en: 'Email',
  emailInfoText_de: 'Sie können uns auch direkt eine E-Mail schreiben:',
  emailInfoText_en: 'You can also email us directly:',
  emailInfoHint_de: 'Bitte geben Sie auch hier möglichst viele Details zu Ihrem Anliegen an.',
  emailInfoHint_en: 'Please provide as many details as possible about your concern here as well.',
  phoneInfoTitle_de: 'Telefon',
  phoneInfoTitle_en: 'Phone',
  phoneInfoText_de: 'Erreichen Sie uns während der Geschäftszeiten:',
  phoneInfoText_en: 'Reach us during business hours:',
  phoneInfoNumber: '+49 123 456789',
});
    
